export const YUP_VALIDATION_ERROR_TYPE = 'YUP_VALIDATION_ERROR'
export const VERIFY_EMAIL_REQUIRE_TYPE = 'VERIFY_EMAIL_REQUIRE'
export const NOT_FOUND = 'NOT_FOUND'
export const EXISTING_SHIPMENT_DRIVER = 'EXISTING_SHIPMENT_DRIVER'
