export enum EStepStatus {
  IDLE = "idle",
  PROGRESSING = "progressing",
  DONE = "done",
  EXPIRE = "expire",
  CANCELLED = "cancelled",
}

export enum EStepDefinition {
  CREATED = "CREATED",
  CASH_VERIFY = "CASH_VERIFY",
  DRIVER_ACCEPTED = "DRIVER_ACCEPTED",
  CONFIRM_DATETIME = "CONFIRM_DATETIME",
  ARRIVAL_PICKUP_LOCATION = "ARRIVAL_PICKUP_LOCATION",
  PICKUP = "PICKUP",
  ARRIVAL_DROPOFF = "ARRIVAL_DROPOFF",
  DROPOFF = "DROPOFF",
  POD = "POD",
  FINISH = "FINISH",
  REJECTED_PAYMENT = "REJECTED_PAYMENT",
  UNINTERESTED_DRIVER = "UNINTERESTED_DRIVER",
  REFUND = "REFUND",
  OTHER = "OTHER",
  CUSTOMER_CANCELLED = "CUSTOMER_CANCELLED",
  SYSTEM_CANCELLED = "SYSTEM_CANCELLED",
}
